name: Application Accepted
on:
  pull_request_target:
    types: [closed]

jobs:
  get_filename:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      filename: ${{ steps.files.outputs.added }}
    steps:
      # NOTE: commented code is for local testing only and most likely broken.
      # - name: 'local test: get all added files in the PR'
      #   if: ${{ env.ACT }}
      #   id: 'files'
      #   run: echo "::set-output name=added::$(echo applications/workflow_testing1.md5 applications/workflow_testing.md)"

      - name: Get application filename # We assume there's only one
        if: ${{ !env.ACT }}
        id: 'files'
        uses: Ana06/get-changed-files@v2.3.0
        with:
          filter: 'applications/*.md'
          format: 'csv'

  update_google_sheet:
    needs: get_filename
    if: needs.get_filename.outputs.filename
    runs-on: ubuntu-latest
    steps:
      # - name: Local Testing checkout
      #   uses: actions/checkout@master
      #   if: ${{ env.ACT }}

      # - name: Local testing parse files
      #   if: ${{ env.ACT }}
      #   id: grant_parser
      #   uses: Ana06/get-changed-files@v2.0.0
      #   with:
      #     path: "${{ steps.filter.outputs.added }}"

      - name: Checkout
        if: ${{ !env.ACT }}
        uses: actions/checkout@v4

      - name: Parse application file
        if: ${{ !env.ACT }}
        id: grant_parser
        uses: w3f/parse-grant-application-action@v1.2
        with:
          path: "${{ github.workspace }}/${{ needs.get_filename.outputs.filename }}"

      - name: Get current date
        id: date
        run: echo "date=$(date +'%d/%m/%Y')" >> $GITHUB_OUTPUT

      - name: Add entry to Google Sheet
        uses: jroehl/gsheet.action@v2.1.1
        with:
          spreadsheetId: ${{ secrets.SPREADSHEET_ID }}
          commands: |
            [
              {
                "command": "appendData",
                "args":
                {
                  "data": [[
                    "${{ steps.grant_parser.outputs.team_name }}",
                    "${{ steps.grant_parser.outputs.team_name }}",
                    "Open Grants",
                    "${{ steps.grant_parser.outputs.project_name }}",
                    "${{ steps.grant_parser.outputs.address }}",
                    "${{ steps.grant_parser.outputs.contact_name }}",
                    "${{ steps.grant_parser.outputs.contact_name }}",
                    "${{ steps.grant_parser.outputs.contact_title }}",
                    "${{ steps.grant_parser.outputs.contact_email }}",
                    "${{ steps.grant_parser.outputs.country }}",
                    "",
                    "https://github.com/w3f/Grants-Program/pull/${{ github.event.pull_request.number }}",
                    "https://github.com/w3f/Grants-Program/pull/${{ github.event.pull_request.number }}",
                    "USD", "0", "0", "0",
                    "",
                    "${{ steps.grant_parser.outputs.total_cost_dai }}",
                    "${{ steps.grant_parser.outputs.dot_percentage }}",
                    "",
                    "",
                    "Signed",
                    "https://github.com/w3f/Grants-Program/pull/${{ github.event.pull_request.number }}",
                    "${{ steps.date.outputs.date }}"
                  ]],
                  "worksheetTitle": "Legal",
                  "minCol": 1,
                  "valueInputOption": "USER_ENTERED"
                }
               }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}

  welcome_comment:
    needs: get_filename
    if: needs.get_filename.outputs.filename
    runs-on: ubuntu-latest
    steps:
      - name: Leave welcome comment
        uses: thollander/actions-comment-pull-request@1.0.1
        with:
          message: > 
            Congratulations and welcome to the Web3 Foundation Grants Program! Please refer to our
            [Milestone Delivery repository](https://github.com/w3f/Grant-Milestone-Delivery/) for
            instructions on how to submit milestones and invoices, our
            [FAQ](https://grants.web3.foundation/docs/faq) for frequently asked questions and the
            [support section on our website](https://grants.web3.foundation/docs/Introduction/support)
            for more ways to find answers to your questions. <br/><br/>
            Before you start, take a moment to read through our
            [announcement guidelines](https://grants.web3.foundation/docs/Support%20Docs/announcement-guidelines)
            for all communications related to the grant or make them known to the right person in your organisation.
            In particular, please <b>don't announce the grant publicly before at least the first milestone of your
            project has been approved.</b> At that point or shortly before, you can get in touch with us at
            grantsPR@web3.foundation and we'll be happy to collaborate on an announcement about the work youâ€™re doing.<br/><br/>
            Also, if you haven't yet, consider signing up for the [Polkadot Alpha Program](https://polkadot.network/development/alpha/). 
            The program offers plenty of resources for people building on Polkadot.
            Lastly, please remember to let us know in case you run into any delays or deviate from the deliverables
            in your application. You can either leave a comment here or directly request to amend your application
            via PR. We wish you luck with your project! :rocket:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
