name: comment_on_label

on:
  pull_request_target:
    types: [labeled]

jobs:
  request_details:
    if: github.event.label.name == 'details missing'
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@1.0.2
        with:
          message: > 
            Thank you for submitting a grant application.<br/>
            
            We've assessed your submission and have found that it requires a higher level
            of technical detail in order to be considered for review. We encourage you to
            expand on it by providing a more precise specification/technical details. The
            [section on project details](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#project-details)
            in the application template is a good reference as to what type of information
            we expect applicants to provide, and these
            [category-specific requirements](https://grants.web3.foundation/docs/Support%20Docs/grant_guidelines_per_category)
            contain more precise guidelines depending on what type of software you're building.<br/>

            An area of the application that we often find to be insufficiently elaborated are the
            milestone deliverables. At a minimum, please indicate what languages/technologies
            you will be using to implement each deliverable, and provide a technical summary
            of its expected functionality. Note that deliverables should be tangible, reusable
            by other teams and in most cases not already present in the ecosystem. If they are,
            you will need to provide a comparison to existing implementations and explain why
            it makes sense to fund your approach. Also see our
            [FAQ](https://grants.web3.foundation/docs/faq#what-activitiespositions-do-you-fund)
            for a breakdown of what we fund and what we don't.<br/>

            Let us know as soon as you're done with your changes, and we'll give your application another look!
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  private_conversation:
    if: github.event.label.name == 'discussion private'
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@1.0.2
        with:
          message: > 
            The applicant has requested the discussion of the application to happen in a private chat room. 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
